# Generated by Django 2.2.7 on 2019-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0006_auto_20191129_0555'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_music', to='mainservice.Music'),
        ),
    ]
