# Generated by Django 2.2.7 on 2019-11-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_music_user_like_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_user',
            name='like_posts',
        ),
    ]
