# Generated by Django 2.2.7 on 2019-11-30 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_no', models.IntegerField(primary_key=True, serialize=False)),
                ('music_title', models.CharField(max_length=45)),
                ('music_composer', models.CharField(max_length=45)),
                ('music_album', models.CharField(max_length=45)),
                ('music_release_date', models.DateTimeField(verbose_name='date published')),
                ('music_genre', models.CharField(max_length=45)),
                ('music_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=10)),
                ('singer_debut', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User_membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly', models.BooleanField(null=True)),
                ('monthly', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play_list',
            fields=[
                ('pname', models.CharField(default='unknowplaylist', max_length=50, primary_key=True, serialize=False)),
                ('music', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainservice.Music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='music_singer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainservice.Singer'),
        ),
    ]
