# Generated by Django 2.2.7 on 2019-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_singer',
            field=models.CharField(default='unknow', max_length=10),
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
    ]
