# Generated by Django 2.2.7 on 2019-11-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
