# Generated by Django 2.2.7 on 2019-11-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainservice', '0002_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_no', models.IntegerField(primary_key=True, serialize=False)),
                ('music_title', models.CharField(max_length=45)),
                ('music_composer', models.CharField(max_length=45)),
                ('music_album', models.CharField(max_length=45)),
                ('music_singer', models.CharField(max_length=45)),
                ('music_release_date', models.DateTimeField(verbose_name='date published')),
                ('music_genre', models.CharField(max_length=45)),
            ],
        ),
    ]
