# Generated by Django 2.2.7 on 2019-11-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0002_auto_20191201_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_singer',
        ),
    ]
