# Generated by Django 2.2.7 on 2019-11-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0003_remove_music_music_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_singer',
            field=models.CharField(default='unknow', max_length=10),
        ),
    ]
