# Generated by Django 2.2.7 on 2019-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0004_play_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_like',
            field=models.BooleanField(default=0),
        ),
    ]
