# Generated by Django 2.2.7 on 2019-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0005_delete_user_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
