# Generated by Django 2.2.7 on 2019-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0005_music_music_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='music_like',
        ),
        migrations.AddField(
            model_name='music',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
