# Generated by Django 2.2.7 on 2019-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0006_auto_20191129_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='like_count',
        ),
        migrations.AddField(
            model_name='music',
            name='music_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
