# Generated by Django 2.2.7 on 2019-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0007_auto_20191130_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='play_list',
            name='music',
            field=models.ManyToManyField(to='mainservice.Music'),
        ),
        migrations.AddField(
            model_name='play_list',
            name='ptitle',
            field=models.CharField(default='untitle playlist', max_length=50),
        ),
    ]
