# Generated by Django 2.2.7 on 2019-11-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0008_auto_20191130_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_list',
            name='music',
        ),
        migrations.RemoveField(
            model_name='play_list',
            name='ptitle',
        ),
        migrations.CreateModel(
            name='List_play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_play_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainservice.Music')),
            ],
        ),
        migrations.AddField(
            model_name='play_list',
            name='each_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainservice.List_play'),
        ),
    ]
