# Generated by Django 2.2.7 on 2019-11-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0009_auto_20191130_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_list',
            name='each_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainservice.List_play'),
        ),
    ]
