# Generated by Django 2.2.7 on 2019-11-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0010_auto_20191130_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_list',
            name='each_list',
        ),
        migrations.AddField(
            model_name='play_list',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainservice.Music'),
        ),
        migrations.DeleteModel(
            name='List_play',
        ),
    ]
