# Generated by Django 2.2.7 on 2019-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainservice', '0011_auto_20191130_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_list',
            name='id',
        ),
        migrations.AddField(
            model_name='play_list',
            name='pname',
            field=models.CharField(default='unknowplaylist', max_length=50, primary_key=True, serialize=False),
        ),
    ]
