# Generated by Django 2.2.7 on 2019-11-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_user',
            name='user_membership',
        ),
        migrations.AddField(
            model_name='user_membership',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Music_user'),
            preserve_default=False,
        ),
    ]
