# Generated by Django 2.2.7 on 2019-11-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191201_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Music_user'),
        ),
    ]
