# Generated by Django 2.2.7 on 2019-11-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191201_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_membership',
            name='username',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Music_user'),
        ),
    ]
