# Generated by Django 2.2.7 on 2019-11-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191201_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_membership',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Music_user'),
        ),
        migrations.AlterField(
            model_name='user_membership',
            name='username',
            field=models.CharField(default='unknown', max_length=10, null=True),
        ),
    ]
